// Generated by scripts/build-client.mjs. Do not edit by hand.

window.__ModuleLoader__.load({
  id: 'dsh-folded-chat',
  factory: (require) => {
    var module = { exports: {} }
    var exports = module.exports

    var name = 'dsh-folded-chat'
    var inject = ['timer', 'slots']

// Pure grouping / visibility policy for the chat fold overlay.
// No DOM. Client runtime and tests share this file.

function nextElementNode(node) {
  let current = node == null ? null : node.nextSibling
  while (current != null && current.nodeType !== 1) current = current.nextSibling
  return current
}

function hasVisibleNonThinkContent(el) {
  if (el == null) return false
  function visit(node) {
    if (node == null) return false
    if (node.nodeType === 3) return String(node.textContent || '').trim() !== ''
    if (node.nodeType !== 1) return false
    if (typeof node.getAttribute === 'function') {
      if (node.getAttribute('data-variant') === 'think') return false
      if (node.getAttribute('data-dsh-folded-chat-bar') != null) return false
      if (node.getAttribute('aria-hidden') === 'true') return false
    }
    const tag = String(node.tagName || '').toLowerCase()
    if (tag === 'img' || tag === 'video' || tag === 'canvas' || tag === 'iframe') return true
    const children = node.childNodes || []
    for (let i = 0; i < children.length; i++) {
      if (visit(children[i])) return true
    }
    return false
  }
  return visit(el)
}

function describeRow(el) {
  if (el == null || typeof el.getAttribute !== 'function') return null
  const think = typeof el.querySelector === 'function'
    ? el.querySelector('[data-variant="think"]')
    : null
  const runningThink = think != null && think.getAttribute('data-state') === 'running'
  const runningSelf = el.getAttribute('data-streaming') != null
    || (typeof el.querySelector === 'function' && el.querySelector('[data-state="running"]') != null)
  return {
    el,
    kind: el.getAttribute('data-chat-flow-kind'),
    anchor: el.getAttribute('data-chat-anchor-key'),
    hasThink: think != null,
    hasVisibleOutput: hasVisibleNonThinkContent(el),
    running: runningThink || runningSelf,
  }
}

function takeProcessPiece(rows, start) {
  const row = rows[start]
  if (row == null || row.kind !== 'assistant-step' || row.hasThink !== true || !row.anchor) return null
  const tools = []
  let running = row.running === true
  let j = start + 1
  while (j < rows.length && rows[j] != null && rows[j].kind === 'tool-call') {
    tools.push(rows[j])
    if (rows[j].running === true) running = true
    j += 1
  }
  return {
    end: j,
    step: row,
    tools,
    running,
    hasVisibleOutput: row.hasVisibleOutput === true,
  }
}

function groupFlowRows(rows) {
  const groups = []
  let i = 0
  let open = null
  while (i < rows.length) {
    const piece = takeProcessPiece(rows, i)
    if (piece == null) {
      if (rows[i] != null && rows[i].kind !== 'tool-call') open = null
      i += 1
      continue
    }
    if (open != null) {
      open.thinkRows.push(piece.step.el)
      if (piece.hasVisibleOutput !== true) open.hideRows.push(piece.step.el)
      for (let t = 0; t < piece.tools.length; t++) open.tools.push(piece.tools[t].el)
      open.toolCount = open.tools.length
      if (piece.running) open.running = true
      if (piece.hasVisibleOutput) open = null
      i = piece.end
      continue
    }
    const group = {
      key: piece.step.anchor,
      startRow: piece.step.el,
      thinkRows: [piece.step.el],
      hideRows: piece.hasVisibleOutput ? [] : [piece.step.el],
      tools: piece.tools.map((item) => item.el),
      toolCount: piece.tools.length,
      running: piece.running,
    }
    groups.push(group)
    open = piece.hasVisibleOutput ? null : group
    i = piece.end
  }
  return groups
}

function defaultFoldState(running, prefs) {
  if (running) return { outer: 'open', inner: 'open', touched: false }
  const collapseOuter = prefs == null || prefs.collapseOuter !== false
  const collapseInner = prefs == null || prefs.collapseInner !== false
  return {
    outer: collapseOuter ? 'collapsed' : 'open',
    inner: collapseInner ? 'collapsed' : 'open',
    touched: false,
  }
}

function reconcileFoldState(existing, running, prefs) {
  if (existing == null) return defaultFoldState(running, prefs)
  if (existing.touched === true) return existing
  return defaultFoldState(running, prefs)
}

function toggleLayer(state, layer) {
  const current = state == null ? defaultFoldState(false, null) : state
  const next = { outer: current.outer, inner: current.inner, touched: true }
  const key = layer === 'inner' ? 'inner' : 'outer'
  next[key] = current[key] === 'open' ? 'collapsed' : 'open'
  return next
}

function processCountParts(thinkCount, toolCount) {
  const thinks = thinkCount > 0 ? thinkCount : 0
  const tools = toolCount > 0 ? toolCount : 0
  const parts = []
  if (thinks > 0) parts.push({ key: 'thinks', count: thinks })
  if (tools > 0) parts.push({ key: 'tools', count: tools })
  if (parts.length === 0) parts.push({ key: 'thinking', count: 0 })
  return parts
}

function visibilityOf(state, toolCount) {
  const outerOpen = state != null && state.outer === 'open'
  const innerOpen = state != null && state.inner === 'open'
  return {
    thinkVisible: outerOpen,
    toolsVisible: outerOpen && innerOpen,
    innerBar: outerOpen && toolCount > 0,
  }
}

const LOCALE_NS = 'dsh-folded-chat'

const COPY = {
  zh: {
    process: '过程',
    processOpen: '过程（点击收起）',
    tools: '工具 ×{count}',
    thinks: '思考 ×{count}',
    thinking: '思考',
    toolCalls: '工具调用',
    toolCallsOpen: '工具调用（点击收起）',
    toolCount: '×{count}',
    cardTitle: '过程折叠',
    cardSubtitle: '聊天主视图',
    enable: '启用',
    collapseProcess: '默认折叠过程',
    collapseTools: '默认折叠工具',
  },
  en: {
    process: 'Process',
    processOpen: 'Process (collapse)',
    tools: 'Tools ×{count}',
    thinks: 'Think ×{count}',
    thinking: 'Thinking',
    toolCalls: 'Tool calls',
    toolCallsOpen: 'Tool calls (collapse)',
    toolCount: '×{count}',
    cardTitle: 'Folded Chat',
    cardSubtitle: 'Chat view',
    enable: 'Enable',
    collapseProcess: 'Collapse process by default',
    collapseTools: 'Collapse tools by default',
  },
}

function detectLang(localeTag) {
  const tag = String(localeTag || '').toLowerCase()
  return tag.indexOf('zh') === 0 ? 'zh' : 'en'
}

function interpolate(template, params) {
  if (params == null) return template
  return String(template).replace(/\{(\w+)\}/g, (match, name) => (
    Object.prototype.hasOwnProperty.call(params, name) ? String(params[name]) : match
  ))
}

function translate(lang, key, params) {
  const table = COPY[lang] || COPY.en
  return interpolate(table[key] || COPY.en[key] || key, params)
}

function createTranslator(ctx) {
  const locale = ctx != null && typeof ctx.get === 'function' ? ctx.get('locale') : null
  if (locale != null && typeof locale.register === 'function' && typeof locale.bind === 'function') {
    const dispose = locale.register(LOCALE_NS, COPY)
    const bound = locale.bind(LOCALE_NS)
    return {
      t: function (key, params) { return bound(key, params) },
      subscribe: typeof locale.subscribe === 'function' ? function (fn) { return locale.subscribe(fn) } : function () { return function () {} },
      dispose: dispose,
    }
  }
  const readLang = function () {
    const doc = typeof document !== 'undefined' ? document : null
    const nav = typeof navigator !== 'undefined' ? navigator : null
    const tag = (doc && doc.documentElement && doc.documentElement.lang) || (nav && nav.language) || 'en'
    return detectLang(tag)
  }
  return {
    t: function (key, params) { return translate(readLang(), key, params) },
    subscribe: function () { return function () {} },
    dispose: function () {},
  }
}

const PREFS_KEY = 'dsh-folded-chat:prefs'

function normalizePrefs(raw) {
  const value = raw && typeof raw === 'object' ? raw : {}
  return {
    enabled: value.enabled !== false,
    collapseOuter: value.collapseOuter !== false,
    collapseInner: value.collapseInner !== false,
  }
}

function loadPrefs(storage) {
  if (storage == null || typeof storage.getItem !== 'function') return normalizePrefs(null)
  try {
    const text = storage.getItem(PREFS_KEY)
    if (text == null || text === '') return normalizePrefs(null)
    return normalizePrefs(JSON.parse(text))
  } catch {
    return normalizePrefs(null)
  }
}

function savePrefs(storage, prefs) {
  const next = normalizePrefs(prefs)
  if (storage != null && typeof storage.setItem === 'function') {
    storage.setItem(PREFS_KEY, JSON.stringify(next))
  }
  return next
}

function createPrefStore(storage) {
  let current = loadPrefs(storage)
  const listeners = new Set()
  return {
    get: function () { return current },
    set: function (patch) {
      current = savePrefs(storage, { ...current, ...patch })
      for (const listener of listeners) listener(current)
      return current
    },
    subscribe: function (listener) {
      listeners.add(listener)
      return function () { listeners.delete(listener) }
    },
  }
}

const SETTINGS_CSS = [
  '.dsh-folded-chat-card{list-style:none;border:1px solid var(--dsw-alias-border-l2,rgba(127,127,127,.3));border-radius:12px;background:var(--dsw-alias-bg-layer-3,transparent)}',
  '.dsh-folded-chat-card[data-open="true"]{background:var(--dsw-alias-bg-layer-2,rgba(127,127,127,.06))}',
  '.dsh-folded-chat-card-header{width:100%;appearance:none;border:0;background:none;font:inherit;color:inherit;text-align:left;cursor:pointer;display:flex;align-items:center;gap:12px;padding:14px 16px;border-radius:12px}',
  '.dsh-folded-chat-card-header:focus-visible{outline:2px solid var(--dsw-alias-brand-primary,#3b82f6);outline-offset:-2px}',
  '.dsh-folded-chat-card-head{flex:1;min-width:0;display:flex;flex-direction:column;gap:2px}',
  '.dsh-folded-chat-card-name{font-size:15px;font-weight:600;line-height:1.4;color:var(--dsw-alias-label-primary,inherit)}',
  '.dsh-folded-chat-card-sub{font-size:13px;line-height:1.4;color:var(--dsw-alias-label-tertiary,#8b93a0)}',
  '.dsh-folded-chat-card-chevron{flex:none;width:1em;height:1em;color:var(--dsw-alias-label-tertiary,#8b93a0);transition:transform .16s}',
  '.dsh-folded-chat-card[data-open="true"] .dsh-folded-chat-card-chevron{transform:rotate(180deg)}',
  '.dsh-folded-chat-card-body{border-top:1px solid var(--dsw-alias-border-l2,rgba(127,127,127,.3));margin:0 16px;padding:4px 0 12px}',
  '.dsh-folded-chat-row{display:flex;align-items:center;justify-content:space-between;gap:16px;padding:10px 0}',
  '.dsh-folded-chat-row + .dsh-folded-chat-row{border-top:1px solid var(--dsw-alias-border-l2,rgba(127,127,127,.18))}',
  '.dsh-folded-chat-row-label{font-size:14px;line-height:1.4;color:var(--dsw-alias-label-primary,inherit)}',
  '.dsh-folded-chat-switch{appearance:none;width:36px;height:20px;flex:none;margin:0;border:0;border-radius:999px;background:var(--dsw-alias-border-l2,rgba(127,127,127,.35));cursor:pointer;position:relative}',
  '.dsh-folded-chat-switch::after{content:"";position:absolute;top:2px;left:2px;width:16px;height:16px;border-radius:50%;background:var(--dsw-alias-bg-layer-3,#fff);transition:transform .16s}',
  '.dsh-folded-chat-switch:checked{background:var(--dsw-alias-brand-primary,#3b82f6)}',
  '.dsh-folded-chat-switch:checked::after{transform:translateX(16px)}',
  '.dsh-folded-chat-switch:focus-visible{outline:2px solid var(--dsw-alias-brand-primary,#3b82f6);outline-offset:2px}',
  '@media (prefers-reduced-motion:reduce){.dsh-folded-chat-card-chevron,.dsh-folded-chat-switch::after{transition:none}}',
].join('\n')

function createSettingsCard(React, store, t) {
  return function FoldSettingsCard() {
    const useState = React.useState
    const [open, setOpen] = useState(false)
    const [prefs, setPrefs] = useState(function () { return store.get() })

    function toggle(key) {
      return function (event) {
        setPrefs(store.set({ [key]: event.target.checked }))
      }
    }

    function row(id, label, checked, onChange) {
      return React.createElement('div', { className: 'dsh-folded-chat-row' },
        React.createElement('label', { className: 'dsh-folded-chat-row-label', htmlFor: id }, label),
        React.createElement('input', {
          id: id,
          className: 'dsh-folded-chat-switch',
          type: 'checkbox',
          role: 'switch',
          checked: checked,
          'aria-checked': checked ? 'true' : 'false',
          onChange: onChange,
        }),
      )
    }

    return React.createElement('li', {
      className: 'dsh-folded-chat-card',
      'data-open': open ? 'true' : 'false',
    },
    React.createElement('button', {
      type: 'button',
      className: 'dsh-folded-chat-card-header',
      'aria-expanded': open ? 'true' : 'false',
      onClick: function () { setOpen(!open) },
    },
    React.createElement('span', { className: 'dsh-folded-chat-card-head' },
      React.createElement('span', { className: 'dsh-folded-chat-card-name' }, t('cardTitle')),
      React.createElement('span', { className: 'dsh-folded-chat-card-sub' }, t('cardSubtitle')),
    ),
    React.createElement('span', {
      className: 'dsh-folded-chat-card-chevron',
      'aria-hidden': 'true',
      dangerouslySetInnerHTML: { __html: '<svg viewBox="0 0 16 16"><path fill="currentColor" d="M3.2 6 8 11.8 12.8 6z"/></svg>' },
    }),
    ),
    open
      ? React.createElement('div', { className: 'dsh-folded-chat-card-body' },
        row('dsh-folded-chat-enable', t('enable'), prefs.enabled, toggle('enabled')),
        row('dsh-folded-chat-outer', t('collapseProcess'), prefs.collapseOuter, toggle('collapseOuter')),
        row('dsh-folded-chat-inner', t('collapseTools'), prefs.collapseInner, toggle('collapseInner')),
      )
      : null,
    )
  }
}

function registerSettings(ctx, React, store, t) {
  const slots = ctx.get('slots')
  if (slots == null || React == null) return function () {}
  const Card = createSettingsCard(React, store, t)
  return slots.inject('settings.plugin.item', function () {
    return slots.register({
      name: 'settings.plugin.item',
      id: 'dsh-folded-chat',
      order: 100,
      label: function () { return t('cardTitle') },
    }, Card)
  })
}

const PLUGIN_ATTR = 'data-dsh-folded-chat'
const BAR_ATTR = 'data-dsh-folded-chat-bar'
const HIDDEN_ATTR = 'data-dsh-folded-chat-hidden'
const STYLE_ATTR = 'data-dsh-folded-chat-style'

const CSS = [
  `body[${PLUGIN_ATTR}] .dsh-folded-chat-bar{display:flex;align-items:center;gap:8px;padding:6px 12px;margin:4px 0 2px;border:1px solid var(--dsw-alias-border-l2,rgba(127,127,127,.3));border-radius:10px;background:var(--dsw-alias-bg-layer-2,rgba(127,127,127,.08));color:var(--dsw-alias-label-secondary,#8b93a0);cursor:pointer;font-size:14px;line-height:1.4;user-select:none}`,
  `body[${PLUGIN_ATTR}] .dsh-folded-chat-bar:hover{background:var(--dsw-alias-interactive-bg-hover,rgba(127,127,127,.16))}`,
  `body[${PLUGIN_ATTR}] .dsh-folded-chat-bar:active{background:var(--dsw-alias-interactive-bg-pressed,rgba(127,127,127,.2))}`,
  `body[${PLUGIN_ATTR}] .dsh-folded-chat-arrow{flex:none;display:inline-flex;width:1em;height:1em;color:var(--dsw-alias-label-secondary,#8b93a0);transition:transform .18s ease}`,
  `body[${PLUGIN_ATTR}] .dsh-folded-chat-arrow svg{display:block;width:1em;height:1em}`,
  `body[${PLUGIN_ATTR}] .dsh-folded-chat-bar[data-open="true"] .dsh-folded-chat-arrow{transform:rotate(90deg)}`,
  `body[${PLUGIN_ATTR}] .dsh-folded-chat-label{white-space:nowrap;overflow:hidden;text-overflow:ellipsis}`,
  `body[${PLUGIN_ATTR}] .dsh-folded-chat-count{flex:none;margin-left:auto;font-size:11px;color:var(--dsw-alias-label-tertiary,#7c8594);background:var(--dsw-alias-bg-layer-1,rgba(127,127,127,.14));border-radius:999px;padding:1px 8px}`,
  `body[${PLUGIN_ATTR}] .dsh-folded-chat-bar[data-fold-layer="inner"]{margin-left:12px;padding:5px 10px}`,
  `@media (prefers-reduced-motion:reduce){body[${PLUGIN_ATTR}] .dsh-folded-chat-arrow{transition:none}}`,
  SETTINGS_CSS,
].join('\n')

function thinkNode(row) {
  return row == null || typeof row.querySelector !== 'function'
    ? null
    : row.querySelector('[data-variant="think"]')
}

function hideNode(el) {
  if (el == null || el.nodeType !== 1) return
  el.setAttribute(HIDDEN_ATTR, '')
  el.style.display = 'none'
}

function showNode(el) {
  if (el == null || el.nodeType !== 1) return
  if (el.getAttribute(HIDDEN_ATTR) == null && el.style.display !== 'none') return
  el.removeAttribute(HIDDEN_ATTR)
  el.style.display = ''
}

function findBar(root, key, layer) {
  const bars = root.querySelectorAll('[' + BAR_ATTR + ']')
  for (let i = 0; i < bars.length; i++) {
    if (bars[i].getAttribute('data-fold-key') === key && bars[i].getAttribute('data-fold-layer') === layer) {
      return bars[i]
    }
  }
  return null
}

function placeBefore(bar, target) {
  const parent = target == null ? null : target.parentNode
  if (parent == null) return
  if (bar.parentNode === parent && nextElementNode(bar) === target) return
  parent.insertBefore(bar, target)
}

function restoreHidden(doc) {
  const marked = doc.querySelectorAll('[' + HIDDEN_ATTR + ']')
  for (let i = 0; i < marked.length; i++) showNode(marked[i])
}

function removeOwnedBars(doc) {
  const bars = doc.querySelectorAll('[' + BAR_ATTR + ']')
  for (let i = 0; i < bars.length; i++) bars[i].remove()
}

function fallbackPrefs() {
  return { enabled: true, collapseOuter: true, collapseInner: true }
}

function createFoldController(doc, options) {
  const getPrefs = options != null && typeof options.getPrefs === 'function' ? options.getPrefs : fallbackPrefs
  const t = options != null && typeof options.t === 'function' ? options.t : function (key) { return key }
  const stateByRoot = new WeakMap()

  function stateMap(root) {
    let map = stateByRoot.get(root)
    if (map == null) {
      map = new Map()
      stateByRoot.set(root, map)
    }
    return map
  }

  function makeBar(key, layer, onToggle) {
    const bar = doc.createElement('div')
    bar.className = 'dsh-folded-chat-bar'
    bar.setAttribute(BAR_ATTR, '')
    bar.setAttribute('data-fold-key', key)
    bar.setAttribute('data-fold-layer', layer)
    bar.setAttribute('role', 'button')
    bar.setAttribute('tabindex', '0')
    const arrow = doc.createElement('span')
    arrow.className = 'dsh-folded-chat-arrow'
    arrow.setAttribute('aria-hidden', 'true')
    arrow.innerHTML = '<svg viewBox="0 0 16 16"><path fill="currentColor" d="M6 3.2 11.8 8 6 12.8z"/></svg>'
    const label = doc.createElement('span')
    label.className = 'dsh-folded-chat-label'
    const count = doc.createElement('span')
    count.className = 'dsh-folded-chat-count'
    bar.appendChild(arrow)
    bar.appendChild(label)
    bar.appendChild(count)
    const toggle = function () { onToggle() }
    bar.addEventListener('click', toggle)
    bar.addEventListener('keydown', function (event) {
      if (event.key === 'Enter' || event.key === ' ') {
        event.preventDefault()
        toggle()
      }
    })
    return bar
  }

  function paintBar(bar, layer, open, counts) {
    const thinkCount = counts && counts.thinkCount ? counts.thinkCount : 0
    const toolCount = counts && counts.toolCount ? counts.toolCount : 0
    bar.setAttribute('data-open', open ? 'true' : 'false')
    bar.setAttribute('aria-expanded', open ? 'true' : 'false')
    const label = bar.querySelector('.dsh-folded-chat-label')
    const count = bar.querySelector('.dsh-folded-chat-count')
    if (layer === 'outer') {
      label.textContent = open ? t('processOpen') : t('process')
      count.textContent = processCountParts(thinkCount, toolCount)
        .map(function (part) { return t(part.key, { count: part.count }) })
        .join(' · ')
    } else {
      label.textContent = open ? t('toolCallsOpen') : t('toolCalls')
      count.textContent = t('toolCount', { count: toolCount })
    }
  }

  function syncRoot(root) {
    const raw = root.querySelectorAll('[data-chat-flow-kind]')
    const rows = []
    for (let i = 0; i < raw.length; i++) {
      const described = describeRow(raw[i])
      if (described != null) rows.push(described)
    }
    const groups = groupFlowRows(rows)
    const map = stateMap(root)
    const live = new Set()

    for (const group of groups) {
      live.add(group.key)
      const next = reconcileFoldState(map.get(group.key), group.running, getPrefs())
      map.set(group.key, next)
      const vis = visibilityOf(next, group.toolCount)

      let outer = findBar(root, group.key, 'outer')
      if (outer == null) {
        outer = makeBar(group.key, 'outer', function () {
          map.set(group.key, toggleLayer(map.get(group.key), 'outer'))
          syncRoot(root)
        })
      }
      paintBar(outer, 'outer', next.outer === 'open', {
        thinkCount: group.thinkRows.length,
        toolCount: group.toolCount,
      })
      placeBefore(outer, group.startRow)

      for (let r = 0; r < group.thinkRows.length; r++) {
        const think = thinkNode(group.thinkRows[r])
        if (vis.thinkVisible) showNode(think)
        else hideNode(think)
      }
      for (let h = 0; h < group.hideRows.length; h++) {
        if (vis.thinkVisible) showNode(group.hideRows[h])
        else hideNode(group.hideRows[h])
      }

      if (vis.innerBar) {
        let inner = findBar(root, group.key, 'inner')
        if (inner == null) {
          inner = makeBar(group.key, 'inner', function () {
            map.set(group.key, toggleLayer(map.get(group.key), 'inner'))
            syncRoot(root)
          })
        }
        paintBar(inner, 'inner', next.inner === 'open', { toolCount: group.toolCount })
        placeBefore(inner, group.tools[0])
      } else {
        const inner = findBar(root, group.key, 'inner')
        if (inner != null) inner.remove()
      }

      for (let t = 0; t < group.tools.length; t++) {
        if (vis.toolsVisible) showNode(group.tools[t])
        else hideNode(group.tools[t])
      }
    }

    const bars = root.querySelectorAll('[' + BAR_ATTR + ']')
    for (let i = 0; i < bars.length; i++) {
      const key = bars[i].getAttribute('data-fold-key')
      if (key == null || live.has(key) === false) bars[i].remove()
    }
    for (const key of Array.from(map.keys())) {
      if (live.has(key) === false) map.delete(key)
    }
  }

  function clearState() {
    const columns = doc.querySelectorAll('[data-conversation-scroll]')
    for (let i = 0; i < columns.length; i++) stateByRoot.delete(columns[i])
  }

  function sync() {
    const prefs = getPrefs()
    if (prefs.enabled === false) {
      restoreHidden(doc)
      removeOwnedBars(doc)
      if (doc.body) doc.body.removeAttribute(PLUGIN_ATTR)
      return
    }
    if (doc.body) doc.body.setAttribute(PLUGIN_ATTR, '')
    const columns = doc.querySelectorAll('[data-conversation-scroll]')
    if (columns.length === 0) return
    for (let i = 0; i < columns.length; i++) syncRoot(columns[i])
  }

  function dispose() {
    restoreHidden(doc)
    removeOwnedBars(doc)
    if (doc.body) doc.body.removeAttribute(PLUGIN_ATTR)
    const style = doc.head == null ? null : doc.head.querySelector('[' + STYLE_ATTR + ']')
    if (style != null) style.remove()
  }

  return { sync, dispose, clearState }
}

function getReact() {
  try {
    if (typeof require === 'function') return require('react')
  } catch {
    return null
  }
  return null
}

function apply(ctx) {
  const doc = document
  const store = createPrefStore(typeof localStorage === 'undefined' ? null : localStorage)
  const i18n = createTranslator(ctx)
  const controller = createFoldController(doc, {
    getPrefs: function () { return store.get() },
    t: i18n.t,
  })
  const style = doc.createElement('style')
  style.setAttribute(STYLE_ATTR, '')
  style.textContent = CSS
  if (doc.head) doc.head.appendChild(style)

  ctx.effect(function () {
    let scheduled = false
    function requestSync() {
      if (scheduled) return
      scheduled = true
      const run = function () {
        scheduled = false
        controller.sync()
      }
      if (typeof requestAnimationFrame === 'function') requestAnimationFrame(run)
      else run()
    }
    const observer = new MutationObserver(requestSync)
    observer.observe(doc.body, {
      childList: true,
      subtree: true,
      attributes: true,
      attributeFilter: ['data-chat-flow-kind', 'data-chat-anchor-key', 'data-streaming', 'data-variant', 'data-state'],
    })
    const timer = ctx.get('timer')
    const stopTimer = timer == null ? null : timer.interval(function () { controller.sync() }, 1000)
    const stopPrefs = store.subscribe(function () {
      controller.clearState()
      requestSync()
    })
    const stopLocale = i18n.subscribe(function () { requestSync() })
    const stopSettings = registerSettings(ctx, getReact(), store, i18n.t)
    requestSync()
    return function () {
      observer.disconnect()
      if (stopTimer != null) stopTimer()
      stopPrefs()
      stopLocale()
      if (typeof stopSettings === 'function') stopSettings()
      i18n.dispose()
      controller.dispose()
    }
  })
}


    exports.name = name
    exports.inject = inject
    exports.apply = apply
    return module.exports
  },
})
